# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imagepair.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='imagepair.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0fimagepair.proto\"7\n\tImagePair\x12\x0e\n\x06image1\x18\x01 \x02(\x0c\x12\x0e\n\x06image2\x18\x02 \x02(\x0c\x12\n\n\x02id\x18\x03 \x01(\t')
)




_IMAGEPAIR = _descriptor.Descriptor(
  name='ImagePair',
  full_name='ImagePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image1', full_name='ImagePair.image1', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image2', full_name='ImagePair.image2', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='ImagePair.id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['ImagePair'] = _IMAGEPAIR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImagePair = _reflection.GeneratedProtocolMessageType('ImagePair', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEPAIR,
  __module__ = 'imagepair_pb2'
  # @@protoc_insertion_point(class_scope:ImagePair)
  ))
_sym_db.RegisterMessage(ImagePair)


# @@protoc_insertion_point(module_scope)
