# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: justbytes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import attributes_pb2 as attributes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='justbytes.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0fjustbytes.proto\x1a\x10\x61ttributes.proto\"M\n\tJustBytes\x12\x10\n\x08\x63ontents\x18\x01 \x02(\x0c\x12\n\n\x02id\x18\x02 \x01(\t\x12\"\n\nattributes\x18\x03 \x01(\x0b\x32\x0e.AttributeList')
  ,
  dependencies=[attributes__pb2.DESCRIPTOR,])




_JUSTBYTES = _descriptor.Descriptor(
  name='JustBytes',
  full_name='JustBytes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contents', full_name='JustBytes.contents', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='JustBytes.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='JustBytes.attributes', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=114,
)

_JUSTBYTES.fields_by_name['attributes'].message_type = attributes__pb2._ATTRIBUTELIST
DESCRIPTOR.message_types_by_name['JustBytes'] = _JUSTBYTES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JustBytes = _reflection.GeneratedProtocolMessageType('JustBytes', (_message.Message,), dict(
  DESCRIPTOR = _JUSTBYTES,
  __module__ = 'justbytes_pb2'
  # @@protoc_insertion_point(class_scope:JustBytes)
  ))
_sym_db.RegisterMessage(JustBytes)


# @@protoc_insertion_point(module_scope)
