# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stringdict.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stringdict.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x10stringdict.proto\"0\n\x12StringKeyValuePair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"0\n\nStringDict\x12\"\n\x05pairs\x18\x01 \x03(\x0b\x32\x13.StringKeyValuePair')
)




_STRINGKEYVALUEPAIR = _descriptor.Descriptor(
  name='StringKeyValuePair',
  full_name='StringKeyValuePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='StringKeyValuePair.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='StringKeyValuePair.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=68,
)


_STRINGDICT = _descriptor.Descriptor(
  name='StringDict',
  full_name='StringDict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pairs', full_name='StringDict.pairs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=118,
)

_STRINGDICT.fields_by_name['pairs'].message_type = _STRINGKEYVALUEPAIR
DESCRIPTOR.message_types_by_name['StringKeyValuePair'] = _STRINGKEYVALUEPAIR
DESCRIPTOR.message_types_by_name['StringDict'] = _STRINGDICT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StringKeyValuePair = _reflection.GeneratedProtocolMessageType('StringKeyValuePair', (_message.Message,), dict(
  DESCRIPTOR = _STRINGKEYVALUEPAIR,
  __module__ = 'stringdict_pb2'
  # @@protoc_insertion_point(class_scope:StringKeyValuePair)
  ))
_sym_db.RegisterMessage(StringKeyValuePair)

StringDict = _reflection.GeneratedProtocolMessageType('StringDict', (_message.Message,), dict(
  DESCRIPTOR = _STRINGDICT,
  __module__ = 'stringdict_pb2'
  # @@protoc_insertion_point(class_scope:StringDict)
  ))
_sym_db.RegisterMessage(StringDict)


# @@protoc_insertion_point(module_scope)
