# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timestamp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='timestamp.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0ftimestamp.proto\"2\n\tTimeStamp\x12\x13\n\x0b\x64\x65scription\x18\x01 \x02(\t\x12\x10\n\x08unixtime\x18\x02 \x02(\x01\",\n\rTimeStampList\x12\x1b\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\n.TimeStamp')
)




_TIMESTAMP = _descriptor.Descriptor(
  name='TimeStamp',
  full_name='TimeStamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='TimeStamp.description', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unixtime', full_name='TimeStamp.unixtime', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=69,
)


_TIMESTAMPLIST = _descriptor.Descriptor(
  name='TimeStampList',
  full_name='TimeStampList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='TimeStampList.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=115,
)

_TIMESTAMPLIST.fields_by_name['entries'].message_type = _TIMESTAMP
DESCRIPTOR.message_types_by_name['TimeStamp'] = _TIMESTAMP
DESCRIPTOR.message_types_by_name['TimeStampList'] = _TIMESTAMPLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeStamp = _reflection.GeneratedProtocolMessageType('TimeStamp', (_message.Message,), dict(
  DESCRIPTOR = _TIMESTAMP,
  __module__ = 'timestamp_pb2'
  # @@protoc_insertion_point(class_scope:TimeStamp)
  ))
_sym_db.RegisterMessage(TimeStamp)

TimeStampList = _reflection.GeneratedProtocolMessageType('TimeStampList', (_message.Message,), dict(
  DESCRIPTOR = _TIMESTAMPLIST,
  __module__ = 'timestamp_pb2'
  # @@protoc_insertion_point(class_scope:TimeStampList)
  ))
_sym_db.RegisterMessage(TimeStampList)


# @@protoc_insertion_point(module_scope)
